### ISSUE TITLE
Command list

### ISSUE THREAD

**Issue by SaucyBoyTheSecond** [adafruit/Adafruit_AM2320#10]
Hello,
I was wondering if there is a command list so i can better understand how the code functions. I wanted to use this in a school project, but i need to create flowchart with it, the specific command i am looking for is from the demo and is as follow: 
Adafruit_AM2320 am2320 = Adafruit_AM2320();
any answers are appreciated

**Comment by ladyada** [comment]
doxygen is here
http://adafruit.github.io/Adafruit_AM2320/html/index.html
all other code is in the examples and source :)
