### ISSUE TITLE
Humidity data I2C Error - ESP32

### ISSUE THREAD

**Issue by ipavlyk23** [adafruit/Adafruit_AM2320#13]
Hardware: DOIT ESP32 DEVKIT V1
ISSUE: When the example is running the Hum: value is not displayed.
![Screenshot_1](https://github.com/adafruit/Adafruit_AM2320/assets/74768775/e54881ec-9028-4f3d-a219-65935f2dd6b8)

Possible solution: added the delay() function between 17 and 18 rows:
Serial.print("Temp: "); Serial.println(am2320.readTemperature());
delay(100);
Serial.print("Hum: "); Serial.println(am2320.readHumidity());
![Screenshot_2](https://github.com/adafruit/Adafruit_AM2320/assets/74768775/dd984441-9b2b-4ce7-b57a-f2f5b9163180)

**Comment by ipavlyk23** [comment]
Hardware: DOIT ESP32 DEVKIT V1
ISSUE: When the example is running the Hum: value is not displayed.
![Screenshot_1](https://github.com/adafruit/Adafruit_AM2320/assets/74768775/f82905b2-9f57-49a4-95e3-febec73bd8fd)
Possible solution: added the delay() function between 17 and 18 rows:
  Serial.print("Temp: "); Serial.println(am2320.readTemperature());
  delay(100);
  Serial.print("Hum: "); Serial.println(am2320.readHumidity());

**Comment by tyeth** [comment]
Hi @ipavlyk23 - Thanks for reporting this, luckily I just received one this weekend so can look immediately.
I've had a quick test on an Adafruit ESP32 Feather v2 with the sensor connected to the StemmaQT / qwiic connector (i2c cable) and can confirm recreating the issue. 

Adding the delay gives me humidity too, but I see a spurious error on the first temperature reading with the basic example. The datasheet says to give 2seconds to stabilise after power-on, so adding a 2second wait at the end of setup removes the first temperature i2c `#263` error, and the humidity errors remain, but the i2c bus detect does now show detected on the second call.

There is a similar report in circuitpython, with a 30ms delay minimum (I found that not enough in arduino). The datasheet mentions after having a read it will return to passive sleep mode until the next wake command, so it's possible we are attempting to communicate during this period.

 I've increase the delay in readRegister32, from 10ms to 100ms upon failure, with a retry if the read command also fails. 

The readings can now be called in a tight loop, and as expected they only change every two seconds.
