### ISSUE TITLE
I2C target address 0x5c not acknowledged!

### ISSUE THREAD

**Issue by akremkh99** [adafruit/Adafruit_AM2320#15]
#include <stdint.h>
#include <stddef.h>
#include <unistd.h>

/* Driver Header files */
#include <ti/drivers/GPIO.h>
#include <ti/drivers/I2C.h>
#include <ti/display/Display.h>
#include <Adafruit_AM2320.h>
/* Driver configuration */
#include "ti_drivers_config.h"

#define TASKSTACKSIZE 640

/* I2C target address for the AM2320 sensor */
#define AM2320_ADDRESS 0x5C

static uint8_t targetAddress;
static Display_Handle display;

static void i2cErrorHandler(I2C_Transaction *transaction, Display_Handle display);

/*
 *  ======== mainThread ========
 */
float Adafruit_AM2320_readTemperature(Adafruit_AM2320 *sensor)
{
    uint8_t txBuffer[3];
    uint8_t rxBuffer[6];
    I2C_Transaction i2cTransaction;

    /* Prepare the I2C transaction to read temperature data */
    txBuffer[0] = AM2320_CMD_READREG;
    txBuffer[1] = AM2320_REG_TEMP_H;
    txBuffer[2] = 2; // Read 2 bytes for temperature

    i2cTransaction.writeBuf   = txBuffer;
    i2cTransaction.writeCount = 3;
    i2cTransaction.readBuf    = rxBuffer;
    i2cTransaction.readCount  = 10;
    i2cTransaction.arg = NULL;
    i2cTransaction.targetAddress = AM2320_ADDRESS;

    /* Perform the I2C transaction */
    if (!I2C_transfer(sensor->i2c, &i2cTransaction))
    {
        /* Handle I2C transaction error */
        return -1.0f;
    }

    /* Parse the temperature data from the received buffer */
    int16_t temperature_raw = (rxBuffer[4] << 8) | rxBuffer[5];
    float temperature = temperature_raw / 10.0f;

    return temperature;
}
float Adafruit_AM2320_readHumidity(Adafruit_AM2320 *sensor)
{
    uint8_t txBuffer[3];
    uint8_t rxBuffer[6];
    I2C_Transaction i2cTransaction;

    /* Prepare the I2C transaction to read humidity data */
    txBuffer[0] = AM2320_CMD_READREG;
    txBuffer[1] = AM2320_REG_HUM_H;
    txBuffer[2] = 2; // Read 2 bytes for humidity

    i2cTransaction.writeBuf   = txBuffer;
    i2cTransaction.writeCount = 3;
    i2cTransaction.readBuf    = rxBuffer;
    i2cTransaction.readCount  = 6;
    i2cTransaction.arg = NULL;
    i2cTransaction.targetAddress = AM2320_ADDRESS;

    /* Perform the I2C transaction */
    if (!I2C_transfer(sensor->i2c, &i2cTransaction))
    {
        /* Handle I2C transaction error */
        return -1.0f;
    }

    /* Parse the humidity data from the received buffer */
    uint16_t humidity_raw = (rxBuffer[2] << 8) | rxBuffer[3];
    float humidity = humidity_raw / 10.0f;

    return humidity;
}

void *mainThread(void *arg0)
{
    int16_t temperature;
    uint16_t humidity;
    uint8_t rxBuffer[6];
    I2C_Handle i2c;
    I2C_Params i2cParams;
    I2C_Transaction i2cTransaction;

    /* Call driver init functions */
    Display_init();
    GPIO_init();
    I2C_init();

    /* Open the UART display for output */
    display = Display_open(Display_Type_UART, NULL);
    if (display == NULL)
    {
        while (1) {}
    }

    /* Create I2C for usage */
    I2C_Params_init(&i2cParams);
    i2cParams.bitRate = I2C_400kHz;
    i2c               = I2C_open(CONFIG_I2C_TMP, &i2cParams);
    if (i2c == NULL)
    {
        Display_printf(display, 0, 0, "Error Initializing I2C\n");
        while (1) {}
    }
    else
    {
        Display_printf(display, 0, 0, "I2C Initialized!\n");
    }

    /* Common I2C transaction setup */
    i2cTransaction.writeBuf   = NULL;
    i2cTransaction.writeCount = 0;
    i2cTransaction.readBuf    = rxBuffer;
    i2cTransaction.readCount  = 6;
    i2cTransaction.arg = NULL;

    /* Set target address to the AM2320 sensor */
    i2cTransaction.targetAddress = AM2320_ADDRESS;

    /* Perform a single I2C transaction to read temperature and humidity data */
    if (I2C_transfer(i2c, &i2cTransaction))
    {
        /* Parse temperature and humidity data from the received buffer */
        humidity = (rxBuffer[2] << 8) | rxBuffer[3];
        temperature = (rxBuffer[4] << 8) | rxBuffer[5];

        /* Convert raw temperature data to Celsius */
        temperature = temperature / 10;

        Display_printf(display, 0, 0, "Temperature: %d C\n", temperature);
        Display_printf(display, 0, 0, "Humidity: %d %%\n", humidity);
    }
    else
    {
        i2cErrorHandler(&i2cTransaction, display);
    }

    I2C_close(i2c);
    Display_printf(display, 0, 0, "I2C closed!");

    return (NULL);
}

/*
 *  ======== i2cErrorHandler ========
 */
static void i2cErrorHandler(I2C_Transaction *transaction, Display_Handle display)
{
    switch (transaction->status)
    {
        case I2C_STATUS_TIMEOUT:
            Display_printf(display, 0, 0, "I2C transaction timed out!");
            break;
        case I2C_STATUS_CLOCK_TIMEOUT:
            Display_printf(display, 0, 0, "I2C serial clock line timed out!");
            break;
        case I2C_STATUS_ADDR_NACK:
            Display_printf(display,
                           0,
                           0,
                           "I2C target address 0x%x not"
                           " acknowledged!",
                           transaction->targetAddress);
            break;
        case I2C_STATUS_DATA_NACK:
            Display_printf(display, 0, 0, "I2C data byte not acknowledged!");
            break;
        case I2C_STATUS_ARB_LOST:
            Display_printf(display, 0, 0, "I2C arbitration to another controller!");
            break;
        case I2C_STATUS_INCOMPLETE:
            Display_printf(display, 0, 0, "I2C transaction returned before completion!");
            break;
        case I2C_STATUS_BUS_BUSY:
            Display_printf(display, 0, 0, "I2C bus is already in use!");
            break;
        case I2C_STATUS_CANCEL:
            Display_printf(display, 0, 0, "I2C transaction cancelled!");
            break;
        case I2C_STATUS_INVALID_TRANS:
            Display_printf(display, 0, 0, "I2C transaction invalid!");
            break;
        case I2C_STATUS_ERROR:
            Display_printf(display, 0, 0, "I2C generic error!");
            break;
        default:
            Display_printf(display, 0, 0, "I2C undefined error case!");
            break;
    }
}

**Comment by caternuson** [comment]
What happens if you use the example from this library?
https://github.com/adafruit/Adafruit_AM2320/blob/master/examples/basic_am2320/basic_am2320.ino

**Comment by akremkh99** [comment]
> What happens if you use the example from this library? https://github.com/adafruit/Adafruit_AM2320/blob/master/examples/basic_am2320/basic_am2320.ino

im using CCS not arduino sir

**Comment by caternuson** [comment]
OK, this an Arduino library. Issues opened here need to be related to using this library code in conjunction with Arduino.

Closing since this is not an issue with this repo code.
